### ISSUE TITLE
Idea ?

### ISSUE THREAD

**Issue by NewRedsquare** [atommarvel/shears-for-kutt#2]
Hello and thank you for beginning this work !

I'm not a Java expert at ALL, but maybe using another android app as source of inspiration may help you ?
I found this : https://play.google.com/store/apps/details?id=net.inscomers.yourls & https://github.com/mwllgr/ic-yourls-android , it's for yourls but it also works with an API system. The UI and the way it works seems perfect for myself. Sadly, not github repo nor licence :(

**Comment by atommarvel** [comment]
This wireframe should give an idea of the functionality that is currently planned: https://github.com/atommarvel/kutt-android/blob/main/data/kutt-android-wireframe.gif

Anything you were specifically thinking about?

**Comment by NewRedsquare** [comment]
The best feature of this application is the ability to copy and automatically shorten the url via the context menu without having to manually go into the application.
This way the short link is directly copied to the clipboard

**Comment by atommarvel** [comment]
That sounds really useful! Do you think you could do a screen recording of it in action so I can fully understand how the feature behaves? I'd love to add it to this project if possible.

**Comment by NewRedsquare** [comment]
> That sounds really useful! Do you think you could do a screen recording of it in action so I can fully understand how the feature behaves? I'd love to add it to this project if possible.

I have a G Pixel 5, so recording is easy ! i'll try to send you a video as soon as possible

Btw, i meant this : https://github.com/thedevs-network/kutt/issues/165#issuecomment-493308942

**Comment by abhijithvijayan** [comment]
@atommarvel i guess this is regarding the similar functionality in bit.ly app

when url is selected in browser, it asks for shorten with bit.ly

**Comment by atommarvel** [comment]
I think I get the feature fully now. No need for a video recording I think.

I added the item " Text selection url shortening" to the roadmap found on the readme :)

Feel free to re-open the issue if there's more to discuss!
