### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by NoverNobida** [atommarvel/shears-for-kutt#3]
Any early release avalible?

**Comment by atommarvel** [comment]
Thanks for your interest! I've just added a section on the ReadMe about releases:

> Releases won't be published until the "Release Open Beta" Milestone is reached in the roadmap.
> 
> You can still grab a .zip of the latest build in [GitHub Actions.](https://github.com/atommarvel/shears-for-kutt/actions/workflows/android.yml)
